### ISSUE TITLE
Drag and Drop Error:  Failed prop type

### ISSUE THREAD

**Issue by LawJolla** [ianstormtaylor/slate-drop-or-paste-images#7] opened 2017-04-05 19:48 UTC
First off, incredible work!  I love Slate and the plug ins!

When dragging and dropping an image to Slate, I get:

`Failed prop type: The prop `block` is marked as required in `Leaf`, but its value is `undefined`.`

I can post the full stack trace.  This occurred in Mac OS X Firefox, Safari, and Chrome 57.

For whatever it's worth, I'm developing on localhost:4000 and am getting CORS errors for copy and paste.  I don't know how the internals work... maybe drag and drop is related.

**Comment by webflo** [comment] 2017-04-12 16:35
Confirmed, i have the same issue.

**Comment by ianstormtaylor** [comment] 2017-04-24 19:09
Does this still happen on the newest version of Slate?

**Comment by ianstormtaylor** [comment] 2017-09-13 15:42
This issue hasn't had a response in a while, and it's unclear if it's still present in the latest versions of Slate. To keep the issues easier to manage, since there are so many being opened every day, I'm going to close this old one out. 

But if you notice that the bug is still happening, please feel free to comment and it can be revisited. It might be an edge case that not many people run into, in which case the fastest way to get it fixed would probably be to write a pull request for it.

Thanks for understanding!

**Closed as completed by ianstormtaylor** 2017-09-13 15:42 UTC
